### PR TITLE
Create a tutorial for publishing data package on Datahub.io

### PR DESCRIPTION
**Pull request by lauragift21**
This is a tutorial that walks you through how to publish your data package on Datahub.io

### CODE REVIEW

**Comment by lauragift21** [comment]
I've completed the tutorial for publishing data package @rufuspollock

**Comment by rufuspollock** [comment]
@lauragift21 are you going to update this?

**Comment by lauragift21** [comment]
I'm not sure what you want me to update @rufuspollock. It hasn't been reviewed yet.

**Comment by rufuspollock** [comment]
> I'm not sure what you want me to update @rufuspollock. It hasn't been reviewed yet.

Ahh. I did comments yesterday but had not hit submit review (did not see that). Done now.

@lauragift21

**Comment by lauragift21** [comment]
Haha alright! I will update these changes and push them. @rufuspollock

**Comment by lauragift21** [comment]
DONE. Fixed and implemented feedback for this tutorial. @rufuspollock

**Comment by rufuspollock** [comment]
@lauragift21 👏

**Pull request merged**
